/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Lab2;

import java.awt.Color;
import java.io.File;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Tho
 */
public class NangCao extends javax.swing.JFrame {
        java.util.List<Cauhoi> list =new ArrayList<>();
        int inDexRadio =0;
        java.util.List<String> list_dapan=new ArrayList<String>(); 
    /**
     * Creates new form NangCao
     */
    public NangCao() throws IOException {
        initComponents();
        FileReader();
        fill(0);
        lblTong.setText(String.valueOf(list.size()));
        setDapAn();
        getContentPane().setBackground(Color.white);
    }
    private void fill(int index){
        lblCauHoi.setText(list.get(index).getCauhoi());
        rdoDapAn1.setText(list.get(index).getDapan1());
        rdoDapAn2.setText(list.get(index).getDapan2());
        rdoDapAn3.setText(list.get(index).getDapan3());
        rdoDapAn4.setText(list.get(index).getDapan4());
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grdo = new javax.swing.ButtonGroup();
        lblCauHoi = new javax.swing.JLabel();
        rdoDapAn1 = new javax.swing.JRadioButton();
        rdoDapAn2 = new javax.swing.JRadioButton();
        rdoDapAn3 = new javax.swing.JRadioButton();
        rdoDapAn4 = new javax.swing.JRadioButton();
        btnNext = new javax.swing.JButton();
        btnPrevious = new javax.swing.JButton();
        btnLast = new javax.swing.JButton();
        btnFirst = new javax.swing.JButton();
        btnFinish = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblIndex = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        lblTong = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        lblCau = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblCauHoi.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblCauHoi.setText("1+1 =?");

        grdo.add(rdoDapAn1);
        rdoDapAn1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoDapAn1.setText("0");

        grdo.add(rdoDapAn2);
        rdoDapAn2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoDapAn2.setText("1");

        grdo.add(rdoDapAn3);
        rdoDapAn3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoDapAn3.setText("2");

        grdo.add(rdoDapAn4);
        rdoDapAn4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        rdoDapAn4.setText("3");

        btnNext.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnNext.setText(">>>");
        btnNext.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextActionPerformed(evt);
            }
        });

        btnPrevious.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnPrevious.setText("<<<");
        btnPrevious.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPreviousActionPerformed(evt);
            }
        });

        btnLast.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLast.setText(">|");
        btnLast.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLastActionPerformed(evt);
            }
        });

        btnFirst.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFirst.setText("|<");
        btnFirst.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFirstActionPerformed(evt);
            }
        });

        btnFinish.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnFinish.setText("Finish");
        btnFinish.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinishActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel1.setText("Câu :");

        lblIndex.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblIndex.setText("1");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Trên");

        lblTong.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblTong.setText("0");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Câu ");

        lblCau.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        lblCau.setText("1 :");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addComponent(rdoDapAn4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblCau)
                        .addGap(345, 345, 345)
                        .addComponent(btnFinish))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(222, 222, 222)
                        .addComponent(lblCauHoi, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(rdoDapAn1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(rdoDapAn2))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(rdoDapAn3))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(211, 211, 211)
                        .addComponent(jLabel1)
                        .addGap(18, 18, 18)
                        .addComponent(lblIndex)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel3)
                        .addGap(18, 18, 18)
                        .addComponent(lblTong))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(138, 138, 138)
                        .addComponent(btnFirst)
                        .addGap(18, 18, 18)
                        .addComponent(btnPrevious)
                        .addGap(12, 12, 12)
                        .addComponent(btnNext)
                        .addGap(18, 18, 18)
                        .addComponent(btnLast)))
                .addGap(0, 35, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblCau)
                        .addComponent(jLabel2))
                    .addComponent(btnFinish))
                .addGap(13, 13, 13)
                .addComponent(lblCauHoi)
                .addGap(13, 13, 13)
                .addComponent(rdoDapAn1)
                .addGap(5, 5, 5)
                .addComponent(rdoDapAn2)
                .addGap(5, 5, 5)
                .addComponent(rdoDapAn3)
                .addGap(5, 5, 5)
                .addComponent(rdoDapAn4)
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(lblIndex)
                    .addComponent(jLabel3)
                    .addComponent(lblTong))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnFirst)
                    .addComponent(btnPrevious)
                    .addComponent(btnNext)
                    .addComponent(btnLast))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void getDapAn(){
        if(list_dapan.get(inDexRadio)==null){
            list_dapan.add(inDexRadio,getDapAp());
        }else{
            list_dapan.remove(inDexRadio);
            list_dapan.add(inDexRadio, getDapAp());
        }   
    }
    private void setDapAn(){
        int i=0;
        while(i<list.size()){
            list_dapan.add(null);
            i++;
        }
    }
    private void setChoose(){
        if(rdoDapAn1.getText().equals(list_dapan.get(inDexRadio))){
            rdoDapAn1.setSelected(true);
        }else if(rdoDapAn2.getText().equals(list_dapan.get(inDexRadio))){
           rdoDapAn2.setSelected(true);
        }else if(rdoDapAn3.getText().equals(list_dapan.get(inDexRadio))){
            rdoDapAn3.setSelected(true);
        }else if(rdoDapAn4.getText().equals(list_dapan.get(inDexRadio))){
            rdoDapAn4.setSelected(true);
        }
    }
    private String getDapAp(){
        if(rdoDapAn1.isSelected()){
            return rdoDapAn1.getText();
        }else if(rdoDapAn2.isSelected()){
            return rdoDapAn2.getText();
        }else if(rdoDapAn3.isSelected()){
            return rdoDapAn3.getText();
        }else if(rdoDapAn4.isSelected()){
            return rdoDapAn4.getText();
        }
                return null;
    }
    private String dapAnDeTail(){
        int i=0;
        String ketQuaDetail="Câu hỏi              Đáp án            Câu trả lời của bạn\n";
        while(i<list.size()){
            ketQuaDetail=ketQuaDetail+list.get(i).getCauhoi()+
            "                  "+list.get(i).getKetqua()+
            "                       "+list_dapan.get(i);
            i++;
        }
        return ketQuaDetail;
    }
    private void btnNextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextActionPerformed
        getDapAn();
        inDexRadio++;
        if(inDexRadio==list.size()){
            JOptionPane.showMessageDialog(this, "Đây là câu hỏi cuối cùng rồi");
            inDexRadio--;
        }else{
            fill(inDexRadio);
        }
           lblIndex.setText(String.valueOf(inDexRadio+1));
           lblCau.setText(String.valueOf(inDexRadio+1));
           grdo.clearSelection();
           setChoose();
// TODO add your handling code here:
    }//GEN-LAST:event_btnNextActionPerformed

    private void btnPreviousActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPreviousActionPerformed
        getDapAn();
        inDexRadio--;
        if(inDexRadio==-1){
            JOptionPane.showMessageDialog(this, "Đây là câu hỏi đầu tiên rồi");
            inDexRadio++;
        }else{
            fill(inDexRadio);
        }    
        lblIndex.setText(String.valueOf(inDexRadio+1));
        lblCau.setText(String.valueOf(inDexRadio+1));
        grdo.clearSelection();
        setChoose();
    }//GEN-LAST:event_btnPreviousActionPerformed

    private void btnLastActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLastActionPerformed
        getDapAn();
        inDexRadio=list.size()-1;
        fill(inDexRadio); 
        lblIndex.setText(String.valueOf(inDexRadio+1));
        lblCau.setText(String.valueOf(inDexRadio+1));
        grdo.clearSelection();
        setChoose();
    }//GEN-LAST:event_btnLastActionPerformed

    private void btnFirstActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFirstActionPerformed
        getDapAn();
        inDexRadio=0;
        fill(inDexRadio);
        lblIndex.setText(String.valueOf(inDexRadio+1));
        lblCau.setText(String.valueOf(inDexRadio+1));
        grdo.clearSelection();
        setChoose();
    }//GEN-LAST:event_btnFirstActionPerformed
static String bangDiem="";
    private void btnFinishActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinishActionPerformed
        getDapAn();
        int diem=0;
        int i=0;
        while(i<list.size()){
            if(list.get(i).getKetqua().equals(list_dapan.get(i))){
                diem++;
            }
            i++;
        }
        int chose=JOptionPane.showConfirmDialog(this, "Bạn có muốn hoàn tất không ?");
        if(chose==0){
            JOptionPane.showMessageDialog(this,"Hoàn thành bài thi !");
            bangDiem="Ban đạt được : "+diem+" trên "+list.size()+"\n"+dapAnDeTail();
            dispose();
            BangDiem bd=new BangDiem();
            bd.setVisible(true);
        }
    }//GEN-LAST:event_btnFinishActionPerformed
    private void FileReader() throws IOException{
        File filename=new File("cauhoi.txt");
        try{
            FileReader input =new FileReader(filename);
            int ch=input.read();
            int chay=0;
            while(ch!=-1){
                String cauhoi="",dapan1="",dapan2="",dapan3="",dapan4="",ketqua="";
                //Cau hoi
                while(chay==0){
                    if(String.valueOf((char)ch).equals(" ")){
                        chay=1;ch=input.read();break;
                    }
                    cauhoi=cauhoi+(char)ch;
                    ch=input.read();
                }
//                Tra loi 1
                while(chay==1){
                    if(String.valueOf((char)ch).equals(" ")){
                        chay=2;ch=input.read();break;
                    }
                    dapan1=dapan1+(char)ch;
                    ch=input.read();
                }
                //tra loi 2
                while(chay==2){
                    if(String.valueOf((char)ch).equals(" ")){
                        chay=3;ch=input.read();break;
                    }
                    dapan2=dapan2+(char)ch;
                    ch=input.read();
                }
                //tra loi 3
                while(chay==3){
                    if(String.valueOf((char)ch).equals(" ")){
                        chay=4;ch=input.read();break;
                    }
                    dapan3=dapan3+(char)ch;
                    ch=input.read();
                }
                // tra loi 4
                while(chay==4){
                    if(String.valueOf((char)ch).equals(" ")){
                        chay=5;ch=input.read();break;
                    }
                    dapan4=dapan4+(char)ch;
                    ch=input.read();
                }
                while(chay==5){
                    if(String.valueOf((char)ch).equals(" ")){
                        chay=0;ch=input.read();break;
                    }
                    ketqua=ketqua+(char)ch;
                    ch=input.read();
                }
                Cauhoi qs=new Cauhoi();
                qs.setCauhoi(cauhoi);
                qs.setDapan1(dapan1);
                qs.setDapan2(dapan2);
                qs.setDapan3(dapan3);
                qs.setDapan4(dapan4);
                qs.setKetqua(ketqua);
                list.add(qs);
            }
        }catch(Exception e){}
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NangCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NangCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NangCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NangCao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new NangCao().setVisible(true);
                } catch (IOException ex) {
                    Logger.getLogger(NangCao.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinish;
    private javax.swing.JButton btnFirst;
    private javax.swing.JButton btnLast;
    private javax.swing.JButton btnNext;
    private javax.swing.JButton btnPrevious;
    private javax.swing.ButtonGroup grdo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblCau;
    private javax.swing.JLabel lblCauHoi;
    private javax.swing.JLabel lblIndex;
    private javax.swing.JLabel lblTong;
    private javax.swing.JRadioButton rdoDapAn1;
    private javax.swing.JRadioButton rdoDapAn2;
    private javax.swing.JRadioButton rdoDapAn3;
    private javax.swing.JRadioButton rdoDapAn4;
    // End of variables declaration//GEN-END:variables
}
